### PR TITLE
Fix the #2 issue

### PR DESCRIPTION
**Pull request by MCYBA**
https://github.com/beeedy/selfupdate/issues/2#issue-320124052

### CODE REVIEW

**Comment by erfantkerfan** [comment]
how can I install this version rather than "pip install selfupdate" ?

**Comment by MCYBA** [comment]
> how can I install this version rather than "pip install selfupdate" ?

Just clone this repo and import the members to your code

**Comment by erfantkerfan** [comment]
@beeedy please accept this merge

**Comment by erfantkerfan** [comment]
@beeedy, when do you think the merge will be updated in pip?

**Comment by beeedy** [comment]
Let me refresh myself and see what it will take to get it updated for you guys

**Comment by gregoriopellegrino** [comment]
I need it! 😄

**Comment by erfantkerfan** [comment]
any lock updating PIP?

**Comment by erfantkerfan** [comment]
@beeedy

**Comment by erfantkerfan** [comment]
hey, man are you ganna update pip?
I'm still waiting for you
and checking pipi every day
@beeedy

**Comment by beeedy** [comment]
@erfantkerfan, the update has been pushed. Also (as it is probably clear) I no longer have time or interest in maintaining this repo and would love to pass along ownership to someone that is able to maintain it. Would you be interested?

**Comment by erfantkerfan** [comment]
@beeedy it would be my pleasure to maintain your work.
Its simple with changing owner in github.
How about updating the pip repo? Would you still do that or some how you will change that too?
Could you contact me in telegram about status of pip repo? My id is the same as here

**Pull request merged**
